name: Build

on:
  push:
    branches:
      - main
      - build


jobs:
  build_linux_wheels:
    name: Build ubuntu wheels
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        cibw_python: ["cp38-*"]
        cibw_manylinux: ["manylinux2010"]

    steps:
      - uses: actions/checkout@v2

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.0.1
        env:
            CIBW_BUILD: ${{ matrix.cibw_python }}
            CIBW_BEFORE_BUILD: apt install -y libeigen3-dev
            CIBW_ARCHS_LINUX: auto 
            CIBW_MANYLINUX_X86_64_IMAGE: ${{ matrix.cibw_manylinux }}$

      - uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: ./wheelhouse/*.whl
